# core/export/markdown_exporter.py
"""
Markdown exporter for summaries, notes, and study materials.
"""

from pathlib import Path
from datetime import datetime
from typing import List, Dict, Any, Optional

from utils.logger import get_logger

logger = get_logger("markdown_exporter")


class MarkdownExporter:
    """
    Export study materials to beautifully formatted Markdown.
    
    Features:
    - Summary export with TOC
    - Flashcard export with toggle sections
    - Quiz export with answers
    - Combined study guide export
    
    Example:
        >>> exporter = MarkdownExporter("Biology 101")
        >>> exporter.set_summary("Cell division is...")
        >>> exporter.add_flashcards([{"q": "Q1", "a": "A1"}])
        >>> exporter.export("study_guide.md")
    """
    
    def __init__(self, title: str = "Study Notes"):
        self.title = title
        self.summary: str = ""
        self.key_points: List[str] = []
        self.flashcards: List[Dict[str, str]] = []
        self.quiz: List[Dict[str, Any]] = []
        self.metadata: Dict[str, Any] = {}
        
        logger.info(f"MarkdownExporter initialized: {title}")
    
    def set_summary(self, summary: str, key_points: Optional[List[str]] = None):
        """Set the summary content."""
        self.summary = summary
        if key_points:
            self.key_points = key_points
    
    def add_flashcards(self, flashcards: List[Dict[str, str]]):
        """Add flashcards to export."""
        self.flashcards.extend(flashcards)
    
    def add_quiz(self, quiz: List[Dict[str, Any]]):
        """Add quiz questions to export."""
        self.quiz.extend(quiz)
    
    def set_metadata(self, **kwargs):
        """Set metadata for the export."""
        self.metadata.update(kwargs)
    
    def to_markdown(self, include_toc: bool = True) -> str:
        """
        Generate the complete Markdown document.
        
        Args:
            include_toc: Whether to include table of contents
        
        Returns:
            Formatted Markdown string
        """
        lines = []
        
        # Title and metadata
        lines.append(f"# 📚 {self.title}")
        lines.append("")
        
        # Metadata section
        lines.append(f"*Generated by EduMind on {datetime.now().strftime('%B %d, %Y at %I:%M %p')}*")
        lines.append("")
        
        if self.metadata:
            lines.append("| Attribute | Value |")
            lines.append("|-----------|-------|")
            for key, value in self.metadata.items():
                lines.append(f"| {key} | {value} |")
            lines.append("")
        
        # Table of contents
        if include_toc:
            lines.append("## 📋 Table of Contents")
            lines.append("")
            if self.summary:
                lines.append("- [Summary](#summary)")
            if self.key_points:
                lines.append("- [Key Points](#key-points)")
            if self.flashcards:
                lines.append("- [Flashcards](#flashcards)")
            if self.quiz:
                lines.append("- [Quiz](#quiz)")
            lines.append("")
            lines.append("---")
            lines.append("")
        
        # Summary section
        if self.summary:
            lines.append("## 📝 Summary")
            lines.append("")
            lines.append(self.summary)
            lines.append("")
        
        # Key points section
        if self.key_points:
            lines.append("## 🎯 Key Points")
            lines.append("")
            for i, point in enumerate(self.key_points, 1):
                lines.append(f"{i}. {point}")
            lines.append("")
        
        # Flashcards section
        if self.flashcards:
            lines.append("---")
            lines.append("")
            lines.append("## 🃏 Flashcards")
            lines.append("")
            lines.append(f"*{len(self.flashcards)} cards to review*")
            lines.append("")
            
            for i, card in enumerate(self.flashcards, 1):
                question = card.get('q') or card.get('question', '')
                answer = card.get('a') or card.get('answer', '')
                
                lines.append(f"### Card {i}")
                lines.append("")
                lines.append(f"**Q:** {question}")
                lines.append("")
                lines.append("<details>")
                lines.append("<summary>Show Answer</summary>")
                lines.append("")
                lines.append(f"**A:** {answer}")
                lines.append("")
                lines.append("</details>")
                lines.append("")
        
        # Quiz section
        if self.quiz:
            lines.append("---")
            lines.append("")
            lines.append("## 📋 Quiz")
            lines.append("")
            lines.append(f"*{len(self.quiz)} questions*")
            lines.append("")
            
            for i, q in enumerate(self.quiz, 1):
                question = q.get('question', '')
                options = q.get('options', [])
                answer = q.get('answer', '')
                explanation = q.get('explanation', '')
                
                lines.append(f"### Question {i}")
                lines.append("")
                lines.append(f"**{question}**")
                lines.append("")
                
                for opt in options:
                    lines.append(f"- [ ] {opt}")
                lines.append("")
                
                lines.append("<details>")
                lines.append("<summary>Show Answer</summary>")
                lines.append("")
                lines.append(f"**Correct Answer:** {answer}")
                if explanation:
                    lines.append("")
                    lines.append(f"*{explanation}*")
                lines.append("")
                lines.append("</details>")
                lines.append("")
        
        # Footer
        lines.append("---")
        lines.append("")
        lines.append("*Study materials generated by [EduMind](https://github.com/EduMind) - AI-Powered Study Assistant*")
        
        return "\n".join(lines)
    
    def export(self, filepath: str) -> str:
        """
        Export to a Markdown file.
        
        Args:
            filepath: Output file path
        
        Returns:
            Path to the created file
        """
        path = Path(filepath)
        if not path.suffix:
            path = path.with_suffix('.md')
        
        content = self.to_markdown()
        
        with open(path, 'w', encoding='utf-8') as f:
            f.write(content)
        
        logger.info(f"Exported Markdown to {path}")
        return str(path)
    
    def export_flashcards_only(self, filepath: str) -> str:
        """Export only flashcards in a simple format."""
        path = Path(filepath)
        if not path.suffix:
            path = path.with_suffix('.md')
        
        lines = [f"# {self.title} - Flashcards", ""]
        
        for i, card in enumerate(self.flashcards, 1):
            q = card.get('q') or card.get('question', '')
            a = card.get('a') or card.get('answer', '')
            lines.append(f"## Card {i}")
            lines.append(f"**Q:** {q}")
            lines.append(f"**A:** {a}")
            lines.append("")
        
        with open(path, 'w', encoding='utf-8') as f:
            f.write("\n".join(lines))
        
        return str(path)
    
    def export_quiz_only(self, filepath: str, include_answers: bool = False) -> str:
        """Export only quiz in a printable format."""
        path = Path(filepath)
        if not path.suffix:
            path = path.with_suffix('.md')
        
        lines = [f"# {self.title} - Quiz", ""]
        
        for i, q in enumerate(self.quiz, 1):
            lines.append(f"**{i}. {q.get('question', '')}**")
            lines.append("")
            for opt in q.get('options', []):
                lines.append(f"   {opt}")
            lines.append("")
            
            if include_answers:
                lines.append(f"   *Answer: {q.get('answer', '')}*")
                if q.get('explanation'):
                    lines.append(f"   *{q.get('explanation')}*")
                lines.append("")
        
        with open(path, 'w', encoding='utf-8') as f:
            f.write("\n".join(lines))
        
        return str(path)


class CSVExporter:
    """Simple CSV exporter for data."""
    
    @staticmethod
    def export_flashcards(flashcards: List[Dict[str, str]], filepath: str) -> str:
        """Export flashcards to CSV."""
        import csv
        
        path = Path(filepath)
        if not path.suffix:
            path = path.with_suffix('.csv')
        
        with open(path, 'w', encoding='utf-8', newline='') as f:
            writer = csv.writer(f)
            writer.writerow(['Question', 'Answer'])
            
            for card in flashcards:
                q = card.get('q') or card.get('question', '')
                a = card.get('a') or card.get('answer', '')
                writer.writerow([q, a])
        
        return str(path)
    
    @staticmethod
    def export_quiz(quiz: List[Dict[str, Any]], filepath: str) -> str:
        """Export quiz to CSV."""
        import csv
        
        path = Path(filepath)
        if not path.suffix:
            path = path.with_suffix('.csv')
        
        with open(path, 'w', encoding='utf-8', newline='') as f:
            writer = csv.writer(f)
            writer.writerow(['Question', 'Option A', 'Option B', 'Option C', 'Option D', 'Answer', 'Explanation'])
            
            for q in quiz:
                options = q.get('options', ['', '', '', ''])
                # Pad to 4 options
                while len(options) < 4:
                    options.append('')
                
                writer.writerow([
                    q.get('question', ''),
                    options[0] if options else '',
                    options[1] if len(options) > 1 else '',
                    options[2] if len(options) > 2 else '',
                    options[3] if len(options) > 3 else '',
                    q.get('answer', ''),
                    q.get('explanation', '')
                ])
        
        return str(path)
