# core/export_service.py
"""
Multi-format export service for EduMind.
Supports PDF, Markdown, and plain text export of study materials.
"""

import os
from datetime import datetime
from typing import Dict, Any, Optional


def export_to_markdown(data: Dict[str, Any], file_path: str) -> bool:
    """
    Export study materials as a clean Markdown document.
    
    Args:
        data: dict with keys: title, summary, key_points, quiz, flashcards
        file_path: Output .md file path
    
    Returns:
        True on success
    """
    try:
        lines = []
        
        # Title
        title = data.get('title', 'EduMind Study Guide')
        lines.append(f"# {title}")
        lines.append(f"*Generated by EduMind AI on {datetime.now().strftime('%B %d, %Y at %I:%M %p')}*")
        lines.append("")
        lines.append("---")
        lines.append("")
        
        # Summary
        if data.get('summary'):
            lines.append("## 📝 AI Summary")
            lines.append("")
            lines.append(data['summary'])
            lines.append("")
        
        # Key Points
        if data.get('key_points'):
            lines.append("## 🎯 Key Points")
            lines.append("")
            for point in data['key_points']:
                lines.append(f"- {point}")
            lines.append("")
        
        # Flashcards
        if data.get('flashcards'):
            lines.append("## 🃏 Flashcards")
            lines.append("")
            lines.append("| # | Question | Answer |")
            lines.append("|---|----------|--------|")
            for i, card in enumerate(data['flashcards'], 1):
                q = card.get('q', card.get('question', ''))
                a = card.get('a', card.get('answer', ''))
                lines.append(f"| {i} | {q} | {a} |")
            lines.append("")
        
        # Quiz
        if data.get('quiz'):
            lines.append("## ❓ Practice Quiz")
            lines.append("")
            for i, q in enumerate(data['quiz'], 1):
                lines.append(f"### Question {i}")
                lines.append(f"**{q.get('question', '')}**")
                lines.append("")
                for opt in q.get('options', []):
                    lines.append(f"- {opt}")
                lines.append("")
            
            lines.append("---")
            lines.append("")
            lines.append("### ✅ Answer Key")
            lines.append("")
            for i, q in enumerate(data['quiz'], 1):
                lines.append(f"**Q{i}:** {q.get('answer', '')} — {q.get('explanation', '')}")
            lines.append("")
        
        # Concept Map
        if data.get('concept_map_path') and os.path.exists(data['concept_map_path']):
            lines.append("## 🗺️ Concept Map")
            lines.append("")
            lines.append(f"![Concept Map]({data['concept_map_path']})")
            lines.append("")
        
        # Footer
        lines.append("---")
        lines.append("*Created with EduMind — AI-Powered Study Assistant*")
        
        os.makedirs(os.path.dirname(file_path) or '.', exist_ok=True)
        with open(file_path, 'w', encoding='utf-8') as f:
            f.write('\n'.join(lines))
        return True
    except Exception as e:
        print(f"Markdown export failed: {e}")
        return False


def export_to_text(data: Dict[str, Any], file_path: str) -> bool:
    """Export study materials as plain text."""
    try:
        lines = []
        
        title = data.get('title', 'EduMind Study Guide')
        lines.append(f"{'=' * 60}")
        lines.append(f"  {title.upper()}")
        lines.append(f"  Generated on {datetime.now().strftime('%B %d, %Y at %I:%M %p')}")
        lines.append(f"{'=' * 60}")
        lines.append("")
        
        if data.get('summary'):
            lines.append("SUMMARY")
            lines.append("-" * 40)
            lines.append(data['summary'])
            lines.append("")
        
        if data.get('key_points'):
            lines.append("KEY POINTS")
            lines.append("-" * 40)
            for i, point in enumerate(data['key_points'], 1):
                lines.append(f"  {i}. {point}")
            lines.append("")
        
        if data.get('flashcards'):
            lines.append("FLASHCARDS")
            lines.append("-" * 40)
            for i, card in enumerate(data['flashcards'], 1):
                q = card.get('q', card.get('question', ''))
                a = card.get('a', card.get('answer', ''))
                lines.append(f"  Q{i}: {q}")
                lines.append(f"  A{i}: {a}")
                lines.append("")
        
        if data.get('quiz'):
            lines.append("PRACTICE QUIZ")
            lines.append("-" * 40)
            for i, q in enumerate(data['quiz'], 1):
                lines.append(f"  {i}. {q.get('question', '')}")
                for opt in q.get('options', []):
                    lines.append(f"     {opt}")
                lines.append("")
            
            lines.append("ANSWER KEY")
            lines.append("-" * 40)
            for i, q in enumerate(data['quiz'], 1):
                lines.append(f"  Q{i}: {q.get('answer', '')} - {q.get('explanation', '')}")
        
        os.makedirs(os.path.dirname(file_path) or '.', exist_ok=True)
        with open(file_path, 'w', encoding='utf-8') as f:
            f.write('\n'.join(lines))
        return True
    except Exception as e:
        print(f"Text export failed: {e}")
        return False


def export_to_html(data: Dict[str, Any], file_path: str) -> bool:
    """Export study materials as a styled HTML document (print-friendly)."""
    try:
        title = data.get('title', 'EduMind Study Guide')
        
        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&display=swap');
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        body {{ font-family: 'Inter', sans-serif; background: #0d1b2a; color: #e8edf3; padding: 40px; max-width: 900px; margin: 0 auto; }}
        h1 {{ color: #00d4aa; font-size: 28px; margin-bottom: 8px; }}
        h2 {{ color: #667eea; font-size: 20px; margin-top: 32px; margin-bottom: 12px; border-left: 4px solid #667eea; padding-left: 12px; }}
        h3 {{ color: #f6ad55; font-size: 16px; margin-top: 20px; margin-bottom: 8px; }}
        .subtitle {{ color: #7b8fa3; font-size: 13px; margin-bottom: 24px; }}
        p {{ line-height: 1.7; margin-bottom: 12px; color: #c0ccda; }}
        ul {{ padding-left: 24px; margin-bottom: 16px; }}
        li {{ margin-bottom: 6px; color: #c0ccda; }}
        .card {{ background: #1b2838; border: 1px solid #1e3044; border-radius: 12px; padding: 16px 20px; margin-bottom: 12px; }}
        .card b {{ color: #00d4aa; }}
        table {{ width: 100%; border-collapse: collapse; margin-bottom: 20px; }}
        th {{ background: #1b2838; color: #00d4aa; padding: 10px; text-align: left; border-bottom: 2px solid #1e3044; }}
        td {{ padding: 10px; border-bottom: 1px solid #1e3044; color: #c0ccda; }}
        hr {{ border: none; border-top: 1px solid #1e3044; margin: 24px 0; }}
        .answer-key {{ background: #1b2838; border-radius: 12px; padding: 20px; }}
        @media print {{ body {{ background: white; color: #333; }} h1 {{ color: #333; }} h2 {{ color: #555; }} .card {{ border-color: #ddd; background: #f9f9f9; }} }}
    </style>
</head>
<body>
    <h1>{title}</h1>
    <p class="subtitle">Generated by EduMind AI on {datetime.now().strftime('%B %d, %Y at %I:%M %p')}</p>
    <hr>
"""
        if data.get('summary'):
            html += f"<h2>📝 AI Summary</h2><p>{data['summary']}</p>"
        
        if data.get('key_points'):
            html += "<h2>🎯 Key Points</h2><ul>"
            for p in data['key_points']:
                html += f"<li>{p}</li>"
            html += "</ul>"
        
        if data.get('flashcards'):
            html += "<h2>🃏 Flashcards</h2><table><tr><th>#</th><th>Question</th><th>Answer</th></tr>"
            for i, card in enumerate(data['flashcards'], 1):
                q = card.get('q', card.get('question', ''))
                a = card.get('a', card.get('answer', ''))
                html += f"<tr><td>{i}</td><td>{q}</td><td>{a}</td></tr>"
            html += "</table>"
        
        if data.get('quiz'):
            html += "<h2>❓ Practice Quiz</h2>"
            for i, q in enumerate(data['quiz'], 1):
                html += f'<div class="card"><h3>Q{i}: {q.get("question", "")}</h3><ul>'
                for opt in q.get('options', []):
                    html += f"<li>{opt}</li>"
                html += "</ul></div>"
            
            html += '<hr><div class="answer-key"><h2>✅ Answer Key</h2>'
            for i, q in enumerate(data['quiz'], 1):
                html += f"<p><b>Q{i}: {q.get('answer', '')}</b> — {q.get('explanation', '')}</p>"
            html += "</div>"
        
        html += """
    <hr>
    <p class="subtitle" style="text-align: center;">Created with EduMind — AI-Powered Study Assistant</p>
</body>
</html>"""
        
        os.makedirs(os.path.dirname(file_path) or '.', exist_ok=True)
        with open(file_path, 'w', encoding='utf-8') as f:
            f.write(html)
        return True
    except Exception as e:
        print(f"HTML export failed: {e}")
        return False
